[build]
  command = "gulp build"  
  publish = "dist/html/*"           
  publish = "dist/css/*"
  publish = "dist/images/*"
  publish = "dist/js/*"

[[redirects]]
  from = "/html/*"
  to = "/html/*"
  status = 200
  force = true
