[build]
  command = "gulp dist"
  publish = "dist"  # HTML ファイルのディレクトリ

  from = "/html/*"
  to = "/html/index.html"
  status = 200


[[redirects]]
  from = "/html/*"
  to = "/html/index.html"
  status = 200