[build]
  command = "gulp dist"
  publish = "dist"

[[headers]]
  for = "/*"

[[redirects]]
  from = "/html/*"
  to = "/html/:spalat"
  status = 200

[[redirects]]
  from = "/css/*"
  to = "/css/:splat"
  status = 200

[[redirects]]
  from = "/js/*"
  to = "/js/:splat"
  status = 200